# Generated by Django 4.2.7 on 2023-11-13 18:15

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_seller_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 11, 13, 18, 15, 25, 986042, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
