# Generated by Django 4.1.13 on 2023-11-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_delete_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='updatedON',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
