# Generated by Django 4.2.7 on 2023-11-11 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('discription', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=50)),
                ('prodImage', models.ImageField(upload_to='static/items')),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('idCardNum', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=20)),
                ('items_sells', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item', verbose_name='The Related Producs')),
            ],
        ),
    ]
