# Generated by Django 4.1.13 on 2023-11-16 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_createtime_seller_createtime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='seller',
        ),
    ]
