# Generated by Django 4.1.13 on 2023-11-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_updatedon'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stockQty',
            field=models.IntegerField(default=1),
        ),
    ]
